# -*- coding: utf-8 -*-
"""All numbers with sipcifice difference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZ0Eq7UAxCTBj5Oe_pGESugHtlQqSWRY
"""

N=13
D=2
Low=1
High=13
while Low<=High:
  Mid=(High+Low)//2
  sum_digits=sum(int(i)for i in str(Mid))
  diff=(Mid-sum_digits)
  if diff<=2:
    Low=Mid+1
  else:
    High=Mid-1
    result=N-High
print(result)