# -*- coding: utf-8 -*-
"""count_zeroes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TC7H5U-t-sHtpYLFt4js0FKTRgdA_0ny
"""

def count_zeroes(n):
    if n == 0:
        return 1

    if n < 10:
        return 0

    return (1 if n % 10 == 0 else 0) + count_zeroes(n // 10)


n = int(input("Enter an integer: "))
print("Number of zeroes:", count_zeroes(n))