# -*- coding: utf-8 -*-
"""decimal_to_binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-3qofQeZyUqw4XjtWLcm6WIiSRJAPdd
"""

def decimal_to_binary(n):
    if n == 0:
        return "0"
    elif n == 1:
        return "1"
    return decimal_to_binary(n // 2) + str(n % 2)


n = int(input("Enter a decimal number: "))
print("Binary equivalent:", decimal_to_binary(n))