# -*- coding: utf-8 -*-
"""Last Index Of One.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kR40RX6rxQzJ8z2yapKmTkiHZFxOBPZb
"""

from array import *
arr=array('i',[0,1,1,0,1,0,1,0,1])
index=-1
n=len(arr)
for i in range(n):
  if arr[i]==1:
    index=i
print("Result=",index)