# -*- coding: utf-8 -*-
"""Matrix Multiplication using Nested Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJmoIkT3By-NKABK4LvwVBjENGQ4YFwW
"""

X = [[12, 7, 3],
     [4, 5, 6],
     [7, 8, 9]]
Y = [[5, 8, 1],
     [6, 7, 3],
     [4, 5, 9]]
result = [[0 for _ in range(len(Y[0]))] for _ in range(len(X))]
for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]
print("Resultant Matrix after Multiplication:")
for row in result:
    print(row)