# -*- coding: utf-8 -*-
"""string_length.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1687F1rLtnnDR08k7KCbRb5tgvr0XMnf5
"""

def string_length(s):

    if s == "":
        return 0

    else:
        return 1 + string_length(s[1:])


print(string_length("Hello"))