# -*- coding: utf-8 -*-
"""sum_natural_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6LXt-kq1fhq45x-5kisubmsNzO-0B8L
"""

def sum_natural_numbers(n):

    if n == 1:
        return 1

    else:
        return n + sum_natural_numbers(n - 1)


print(sum_natural_numbers(5))