# -*- coding: utf-8 -*-
"""sum_of_digits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMonWcv30T0m5PIXGtw4HS-eEUDcwkYE
"""

def sum_of_digits(n):
    if n == 0:
        return 0
    return n % 10 + sum_of_digits(n // 10)


n = int(input("Enter a number: "))
print("Sum of digits:", sum_of_digits(n))