# -*- coding: utf-8 -*-
"""Transpose of a Matrix using Nested Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189pnOZ_ocdT_htrIGZ7q2tIsxJf44j7l
"""

X = [[12, 7],
     [4, 5],
     [3, 8]]
result = [[0 for _ in range(len(X))] for _ in range(len(X[0]))]
for i in range(len(X)):
    for j in range(len(X[0])):
        result[j][i] = X[i][j]
print("Transpose of the Matrix:")
for row in result:
    print(row)